version: '3'

services:
  ldap:
    container_name: ldap
    image: osixia/openldap:1.3.0
    ports:
      - "389:389"
      - "636:636"
    command: [--copy-service,  --loglevel, debug]
    environment:
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_DOMAIN=ldap.molgenis.org
      - LDAP_ORGANISATION=MOLGENIS
      - LDAP_CONFIG_PASSWORD=config
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=readonly
      - LDAP_READONLY_USER_PASSWORD=readonly
    networks:
      - ldap
  phpldapadmin:
    container_name: phpldapadmin
    image: osixia/phpldapadmin
    ports:
      - "80:80"
    environment:
      - PHPLDAPADMIN_HTTPS="false"
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
    links:
      - ldap
    depends_on:
      - ldap
    networks:
      - ldap
  rstudio:
    container_name: rstudio
    image: molgenis/rstudio:3.1.0
    volumes: 
        - ~/VisualStudioCodeProjects/ldap/rstudio/rstudio:/etc/pam.d/rstudio
        - ~/VisualStudioCodeProjects/ldap/rstudio/common-auth:/etc/pam.d/common-auth
        - ~/VisualStudioCodeProjects/ldap/rstudio/nsswitch.conf:/etc/nsswitch.conf
    environment:
    - PASSWORD=admin
    ports:
    - "8787:8787"
    links:
      - ldap
    depends_on:
      - ldap
    networks:
      - ldap


networks:
  ldap:
    # use the bridge driver, but enable IPv6
    driver: bridge
